
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: tags_development 
  
   # Suas configurações corretas:
  host: localhost
  port: 5432
  username: postgres
  password: "root"

test:
  <<: *default
  database: tags_test

  host: localhost
  port: 5432
  username: postgres
  password: "root"



production:
  primary: &primary_production
    <<: *default
    database: tags_production
    username: tags
    password: <%= ENV["TAGS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tags_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tags_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tags_production_cable
    migrations_paths: db/cable_migrate
